waypoints:
  spawn:
    name: "Spawn"
    color: 1
    location:
      world: "world"
      x: 0
      y: 100
      z: 0
nametag:
  enabled: false
  below: ""
  above: "%faction_name% DTR: %faction_dtr%"

settings:
  AeroClient-Only:
    enabled: false
    kick-message: "&9[API]&a You cannot join as you are not on Aero Client. Download it at &bAeroClient.tk"