name: AeroClientAPI
version: ${project.version}
main: net.aeroclient.aeroclientapi.AeroClientAPI
authors: [Aero Client Development Team]
description: AeroClientAPI
commands:
  clientlist:
    description: Check who is on Aero Client, CheatBreaker, or Lunar Client!
    aliases:
      - "clients"

  apiinfo:
    description: View the AeroClientAPI information!
    aliases:
      - "APIinfo"
    permission: "aeroclientapi.info"

  apihelp:
    description: View the AeroClientAPI help page!
    aliases:
      - "APIhelp"

  apireload:
    description: Reload the Config!
    aliases:
      - "apireload"
    permission: "aeroclientapi.reload"

  setWaypoint:
    description: Create a waypoint where you are standing!
    aliases:
      - "setwaypoint"
    permission: "aeroclientapi.setwaypoint"

  anotification :
    description: Send notifications to all online Aero Client users!

    aliases:
      - "an"
      - "anoti"
    permission: "aeroclientapi.anotification"

  client:
    description: View information about Aero Client!
    aliases:
      - "aeroclient"
      - "client"

  clientban:
    description: Ban users from Aero Client!
    aliases:
      - "APIban"
      - "clientban"
      - "cban"
    permission: "aeroclientapi.clientban"

  clientunban:
    description: Unban users from Aero Client!
    aliases:
      - "clientunban"
    permission: "aeroclientapi.clientunban"

  staffmods:
    description: Grant a user Staff Modules!
    aliases:
      - "sm"
      - "staffmods"
    permission: "aeroclientapi.admin"

  banwave:
    description: Start an Aero Client banwave!
    aliases:
      - "bw"
    permission: "aeroclientapi.admin"
